### ISSUE TITLE
Editing existing text file broken on iOS

### ISSUE THREAD

**Issue by sdeleuze** [FilenCloudDienste/filen-mobile#261] opened 2023-08-13 20:39 UTC
Hi, it looks like the text edition feature only works for newly created files, but not for existing file (the edit menu is available but only allows to view it).

Could you please fix that bug?

**Comment by Dwynr** [comment] 2024-01-05 02:55
What extension does the file have?

**Comment by sdeleuze** [comment] 2024-01-08 08:23
I think it was `.txt`.

**Comment by Dwynr** [comment] 2024-01-12 02:00
Sorry but I cannot reproduce the issue. Can you provide more information?

**Comment by szapp** [comment] 2024-01-12 08:55
I can reproduce the issue. I tried to capture the problem on video.

iOS 16.7.2, Filen 2.0.61

https://github.com/FilenCloudDienste/filen-mobile/assets/20203034/934fbd24-eb38-4dda-afe6-aa151b6c4bb8

**Comment by Dwynr** [comment] 2024-01-12 11:28
Ah I see, got it. Will be fixed with the new text editor.

**Closed by Dwynr** 2024-01-12 11:28 UTC
